kind: pipeline
name: default

steps:
- name: install
  image: ubuntu
  volumes:
  - name: meteor
    path: /drone/home
  environment:
    HOME: /drone/home
  commands:
    - export PATH="/drone/home/.meteor:$PATH"
    - apt update && apt install curl bzip2 -y
    - if [ ! -e "/drone/home/.meteor" ]; then export HOME=/drone/home; curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh; fi
    - curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh

- name: versions
  image: ubuntu
  volumes:
  - name: meteor
    path: /drone/home
  environment:
    METEOR_ALLOW_SUPERUSER: 'true'
    HOME: /drone/home
  commands:
    - export PATH="/drone/home/.meteor:$PATH"
    - pwd
    - whoami
    - meteor --version
    - meteor npm --versions
    - meteor node -v

- name: npm install
  image: ubuntu
  volumes:
  - name: meteor
    path: /drone/home
  environment:
    TOOL_NODE_FLAGS: --max_old_space_size=3072
    METEOR_ALLOW_SUPERUSER: 'true'
    HOME: /drone/home
  commands:
    - export PATH="/drone/home/.meteor:$PATH"
    - apt update && apt install curl git python g++ build-essential bzip2 -y
    - meteor npm install
    - cd packages/rocketchat-livechat/.app/
    - meteor npm install

- name: lint
  image: ubuntu
  volumes:
  - name: meteor
    path: /drone/home
  environment:
    TOOL_NODE_FLAGS: --max_old_space_size=3072
    METEOR_ALLOW_SUPERUSER: 'true'
    HOME: /drone/home
  commands:
    - export PATH="/drone/home/.meteor:$PATH"
    - meteor npm run lint

- name: test
  image: ubuntu
  volumes:
  - name: meteor
    path: /drone/home
  environment:
    TOOL_NODE_FLAGS: --max_old_space_size=3072
    METEOR_ALLOW_SUPERUSER: 'true'
    HOME: /drone/home
  commands:
    - export PATH="/drone/home/.meteor:$PATH"
    - MONGO_URL=mongodb://mongo:27017 meteor npm run testunit

- name: build
  image: node:8.11
  volumes:
  - name: meteor
    path: /drone/home
  environment:
    TOOL_NODE_FLAGS: --max_old_space_size=3072
    METEOR_ALLOW_SUPERUSER: 'true'
    HOME: /drone/home
  commands:
    - export PATH="/drone/home/.meteor:$PATH"
    - apt update && apt install curl bzip2 -y
    - mkdir /drone/build
    - export METEOR_PROFILE=1000
    - meteor build --server-only --directory --debug /drone/build

services:
- name: mongo
  image: mongo:3.2
  ports:
  - 27017

volumes:
- name: meteor
  temp: {}
