kind: pipeline
name: Build

steps:
- name: install
  image: ubuntu
  commands:
    - whoami
    - sleep 60
    - date

- name: versions
  image: ubuntu
  commands:
    - whoami
    - sleep 50
    - date

- name: test 1
  image: ubuntu
  commands:
    - whomai
    - sleep 40
    - date
  depends_on:
    - versions

- name: test 2
  image: ubuntu
  commands:
    - whoami
    - sleep 120
    - date
  depends_on:
    - versions

- name: deploy
  image: ubuntu
  commands:
    - whoami
    - sleep 20
    - date
  depends_on:
    - test 1
    - test 2

- name: docker image
  image: ubuntu
  commands:
    - whoami
    - sleep 10
    - date
  depends_on:
    - deploy
