kind: pipeline
name: default

steps:
- name: frontend
  image: ubuntu
  commands:
    - apt update && apt install -y git python build-essential
    - ls -l

services:
- name: redis
  image: redis:latest
  ports:
  - 6379
