kind: pipeline
name: default


steps:
- name: frontend
  image: ubuntu
  commands:
    - apt update && apt install curl git python g++ build-essential bzip2 -y
    - export HOME=/drone
    - export PATH="/drone/.meteor:$PATH"
    - if [ ! -e "/drone/.meteor/meteor" ]; then export HOME=/drone; curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh; fi
    - which meteor
    - meteor npm install
    - mkdir /drone/build
    - meteor build --server-only --directory /drone/build

- name: versions
  commands:
  - meteor --version
  - meteor npm --versions
  - meteor node -v
  - git version
