kind: pipeline
name: default

steps:
- name: frontend
  image: ubuntu
  commands:
    - apt update && apt install curl git python g++ build-essential bzip2 -y
    - curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh
    - ls -l
    - meteor npm install

services:
- name: mongo
  image: mongo:3.2
  ports:
  - 27017
